name: Create Cluster

on:
  workflow_dispatch:
    inputs:
      actions:
        type: choice
        description: 'Plan, Apply or Destroy'
        options:
        - plan
        - apply
        - destroy
        required: true
        default: 'plan'

jobs:
  Install-Terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v3

    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Terraform Init
      run: terraform init

    - name: Validation
      run: terraform validate -json
    
  Plan:
    runs-on: ubuntu-latest
    needs: Install-Terraform
    steps:
    - uses: hashicorp/setup-terraform@v3

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Terraform Init
      run: terraform init

    - name: Plan
      if: ${{ github.event.inputs.actions  == 'plan' }}
      run: terraform plan